name: Build and Deploy to Firebase

on:
  push:
    branches: [ "testing" ]

#   pull_request:
#     branches:
#       - testing

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: ./gradlew assembleDebug appDistributionUploadDebug
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/
